local defaults = {}

local colors = require("harmony.colors")
local blend = require("harmony.utils").blend

defaults.themes = {
  ["*"] = {
    bg = { "#111111", "#ffffff" },
    fg = { "#ffffff", "#111111" },
    red = { "#E86671", "#E86671" },
    green = { "#A9DC76", "#A9DC76" },
    yellow = { "#E7C547", "#E7C547" },
    orange = { "#FFA94D", "#FFA94D" },
    blue = { "#7AA2F7", "#7AA2F7" },
    purple = { "#C594C5", "#C594C5" },
    accent = { "#7AA2F7", "#7AA2F7" },

    lightness = 0,

    plugins = {
      "hrsh7th/nvim-cmp",
      "SmiteshP/nvim-navic",
      "folke/todo-comments.nvim",
      "nvim-telescope/telescope.nvim",
      "lukas-reineke/indent-blankline.nvim",
      "nvim-neo-tree/neo-tree.nvim",
      "j-hui/fidget.nvim",
    },

    -- on_change = function() end,

    highlights = {

      -- see :help highlight-groups
      ColorColumn = { bg = colors.bg_negative_1 },
      CurSearch = { bg = colors.bg_3 },
      CursorColumn = { bg = colors.bg_1 },
      Directory = { fg = colors.accent },
      DiffAdd = { fg = colors.green },
      DiffChange = { fg = colors.blue },
      DiffDelete = { fg = colors.red },
      DiffText = { fg = colors.bg_1 },
      EndOfBuffer = { bg = colors.bg_0 },
      ErrorMsg = { fg = colors.red },
      WinSeparator = { fg = colors.bg_4 },
      VertSplit = { fg = colors.bg_4 },
      Folded = { bg = colors.bg_negative_1, fg = colors.blue },
      FoldColumn = { fg = colors.fg_3, bg = colors.bg_0 },
      SignColumn = { bg = colors.bg_0 },
      Substitute = { bg = colors.accent },
      LineNr = { fg = colors.fg_4 },
      CursorLine = { bg = colors.bg_1 },
      CursorLineNr = { bg = colors.bg_1 },
      CursorLineSign = { bg = colors.bg_1 },
      CursorLineFold = { bg = colors.bg_1 },
      MatchParen = { bg = colors.bg_2 },
      ModeMsg = { fg = colors.accent },
      MsgArea = { fg = colors.fg_2 },
      MoreMsg = { fg = colors.accent },
      NonText = { fg = colors.accent },
      Normal = { bg = colors.bg_0, fg = colors.fg_1 },
      NormalFloat = { bg = colors.bg_1, fg = colors.fg_3 },
      FloatBorder = { bg = colors.bg_1, fg = colors.fg_4 },
      NormalNC = { bg = colors.bg_0 },
      Pmenu = { bg = colors.bg_1 },
      PmenuSel = { bg = colors.bg_3 },
      PmenuSbar = { bg = colors.bg_2 },
      PmenuThumb = { bg = colors.fg_4 },
      Question = { fg = colors.yellow },
      QuickFixLine = { bg = colors.bg_2 },
      Search = { bg = colors.bg_2 },
      SpellBad = { undercurl = true, sp = colors.red },
      SpellCap = { undercurl = true, sp = colors.blue },
      SpellLocal = { undercurl = true, sp = colors.blue },
      SpellRare = { undercurl = true, sp = colors.purple },
      StatusLine = { bg = colors.bg_2, fg = colors.fg_2 },
      StatusLineNC = { bg = colors.bg_1, fg = colors.fg_3 },
      TabLine = { fg = colors.fg_3 },
      TabLineSel = { fg = colors.bg_3, bg = colors.accent },
      TabLineFill = { fg = colors.bg_2 },
      Title = { fg = colors.yellow },
      Visual = { bg = colors.bg_2 },
      VisualNOS = { bg = colors.bg_2 },
      WarningMsg = { bg = colors.bg_0, fg = colors.red },
      Whitespace = { fg = colors.fg_3 },
      WildMenu = { bg = colors.bg_3, fg = colors.fg_3 },
      WinBar = { bg = colors.bg_0, fg = colors.fg_3 },
      WinBarNC = { bg = colors.bg_0, fg = colors.fg_3 },

      DiagnosticError = { fg = colors.red },
      DiagnosticWarn = { fg = colors.yellow },
      DiagnosticInfo = { fg = colors.purple },
      DiagnosticHint = { fg = colors.blue },
      DiagnosticVirtualTextError = { fg = colors.red },
      DiagnosticVirtualTextWarn = { fg = colors.yellow },
      DiagnosticVirtualTextInfo = { fg = colors.purple },
      DiagnosticVirtualTextHint = { fg = colors.blue },
      DiagnosticUnderlineError = { sp = colors.red, undercurl = true },
      DiagnosticUnderlineWarn = { sp = colors.yellow, undercurl = true },
      DiagnosticUnderlineInfo = { sp = colors.purple, undercurl = true },
      DiagnosticUnderlineHint = { sp = colors.blue, undercurl = true },
      DiagnosticFloatingError = { fg = colors.red, bg = colors.bg_1 },
      DiagnosticFloatingWarn = { fg = colors.yellow, bg = colors.bg_1 },
      DiagnosticFloatingInfo = { fg = colors.purple, bg = colors.bg_1 },
      DiagnosticFloatingHint = { fg = colors.blue, bg = colors.bg_1 },
      DiagnosticSignError = { fg = colors.red },
      DiagnosticSignWarn = { fg = colors.yellow },
      DiagnosticSignInfo = { fg = colors.purple },
      DiagnosticSignHint = { fg = colors.blue },
      LspReferenceRead = { bg = colors.bg_1 },
      LspReferenceText = { bg = colors.bg_1 },
      LspReferenceWrite = { bg = colors.bg_1 },
    },

    enable = false,
  },
}

return defaults
