local plugins = {}

local colors = require("harmony.colors")

-- stylua: ignore start
plugins["akinsho/bufferline.nvim"] = {
  BufferLineFill                      = { fg = colors.foreground_3, bg = colors.background_negative_2 },
  BufferLineSeparator                 = { fg = colors.background_negative_2, bg = colors.background_negative_2 },
  BufferLineTabSeparator              = { fg = colors.background_negative_2, bg = colors.background_negative_2 },
  BufferLineOffsetSeparator           = { fg = colors.background_0, bg = colors.background_negative_2 },
  BufferLineGroupSeparator            = { fg = colors.foreground_3, bg = colors.background_negative_2 },
  BufferLineGroupLabel                = { fg = colors.background_negative_2, bg = colors.foreground_3 },
  BufferLineInfoDiagnosticVisible     = { fg = colors.foreground_4, bg = colors.background_1 },
  BufferLineDiagnosticVisible         = { fg = colors.foreground_4, bg = colors.background_1 },
  BufferLineHintDiagnosticVisible     = { fg = colors.foreground_4, bg = colors.background_1 },
  BufferLineWarningDiagnosticVisible  = { fg = colors.foreground_4, bg = colors.background_1 },
  BufferLineErrorDiagnosticVisible    = { fg = colors.foreground_4, bg = colors.background_1 },
  BufferLineHintVisible               = { fg = colors.foreground_3, bg = colors.background_1 },
  BufferLineInfoVisible               = { fg = colors.foreground_3, bg = colors.background_1 },
  BufferLineWarningVisible            = { fg = colors.foreground_3, bg = colors.background_1 },
  BufferLineCloseButtonVisible        = { fg = colors.foreground_3, bg = colors.background_1 },
  BufferLineBufferVisible             = { fg = colors.foreground_3, bg = colors.background_1 },
  BufferLineNumbersVisible            = { fg = colors.foreground_3, bg = colors.background_1 },
  BufferLineErrorVisible              = { fg = colors.foreground_3, bg = colors.background_1 },
  BufferLineModifiedVisible           = { fg = colors.foreground_0, bg = colors.background_1 },
  BufferLineSeparatorVisible          = { fg = colors.background_negative_2, bg = colors.background_1 },
  BufferLineIndicatorVisible          = { fg = colors.background_1, bg = colors.background_1 },
  BufferLineDuplicateVisible          = { fg = colors.foreground_3, bg = colors.background_1, italic = true, cterm = { italic = true }, },
  BufferLinePickVisible               = { fg = colors.red, bg = colors.background_1, bold = true, italic = true, cterm = { bold = true, italic = true }},
  BufferLineDiagnosticSelected        = { fg = colors.foreground_1, bg = colors.background_0, bold = true, underline = true, italic = true, sp = colors.accent, cterm = { bold = true, underline = true, italic = true }},
  BufferLineBufferSelected            = { fg = colors.foreground_0, bg = colors.background_0, bold = true, underline = true, italic = true, sp = colors.accent, cterm = { bold = true, underline = true, italic = true }},
  BufferLineNumbersSelected           = { fg = colors.foreground_0, bg = colors.background_0, bold = true, underline = true, italic = true, sp = colors.accent, cterm = { bold = true, underline = true, italic = true }},
  BufferLineHintSelected              = { fg = colors.blue, bg = colors.background_0, bold = true, underline = true, italic = true, sp = colors.accent, cterm = { bold = true, underline = true, italic = true }},
  BufferLineHintDiagnosticSelected    = { fg = colors.blue, bg = colors.background_0, bold = true, underline = true, italic = true, sp = colors.accent, cterm = { bold = true, underline = true, italic = true }},
  BufferLineInfoSelected              = { fg = colors.purple, bg = colors.background_0, bold = true, underline = true, italic = true, sp = colors.accent, cterm = { bold = true, underline = true, italic = true }},
  BufferLineInfoDiagnosticSelected    = { fg = colors.purple, bg = colors.background_0, bold = true, underline = true, italic = true, sp = colors.accent, cterm = { bold = true, underline = true, italic = true }},
  BufferLineWarningSelected           = { fg = colors.yellow, bg = colors.background_0, bold = true, underline = true, italic = true, sp = colors.accent, cterm = { bold = true, underline = true, italic = true }},
  BufferLineWarningDiagnosticSelected = { fg = colors.yellow, bg = colors.background_0, bold = true, underline = true, italic = true, sp = colors.accent, cterm = { bold = true, underline = true, italic = true }},
  BufferLineErrorSelected             = { fg = colors.red, bg = colors.background_0, bold = true, underline = true, italic = true, sp = colors.accent, cterm = { bold = true, underline = true, italic = true }},
  BufferLineErrorDiagnosticSelected   = { fg = colors.red, bg = colors.background_0, bold = true, underline = true, italic = true, sp = colors.accent, cterm = { bold = true, underline = true, italic = true }},
  BufferLinePickSelected              = { fg = colors.red, bg = colors.background_0, bold = true, underline = true, italic = true, sp = colors.accent, cterm = { bold = true, underline = true, italic = true }},
  BufferLineDuplicateSelected         = { fg = colors.foreground_3, bg = colors.background_0, underline = true, italic = true, sp = colors.accent, cterm = { underline = true, italic = true }},
  BufferLineSeparatorSelected         = { fg = colors.background_negative_2, bg = colors.background_0, underline = true, sp = colors.accent, cterm = { underline = true }},
  BufferLineTabSeparatorSelected      = { fg = colors.background_negative_2, bg = colors.background_0, underline = true, sp = colors.accent, cterm = { underline = true }},
  BufferLineCloseButtonSelected       = { fg = colors.foreground_0, bg = colors.background_0, underline = true, sp = colors.accent, cterm = { underline = true }},
  BufferLineModifiedSelected          = { fg = colors.foreground_0, bg = colors.background_0, underline = true, sp = colors.accent, cterm = { underline = true }},
  BufferLineTabSelected               = { fg = colors.accent, bg = colors.background_0, underline = true, sp = colors.accent, cterm = { underline = true }},
  BufferLineIndicatorSelected         = { fg = colors.accent, bg = colors.background_0, underline = true, sp = colors.accent, cterm = { underline = true }},
  BufferLineDuplicate                 = { fg = colors.foreground_3, bg = colors.background_negative_1, italic = true, cterm = { italic = true }},
  BufferLinePick                      = { fg = colors.red, bg = colors.background_negative_1, bold = true, italic = true, cterm = { bold = true, italic = true }},
  BufferLineDiagnostic                = { fg = colors.foreground_4, bg = colors.background_negative_1 },
  BufferLineTab                       = { fg = colors.foreground_3, bg = colors.background_negative_1 },
  BufferLineBuffer                    = { fg = colors.foreground_3, bg = colors.background_negative_1 },
  BufferLineBackground                = { fg = colors.foreground_3, bg = colors.background_negative_1 },
  BufferLineNumbers                   = { fg = colors.foreground_3, bg = colors.background_negative_1 },
  BufferLineCloseButton               = { fg = colors.foreground_3, bg = colors.background_negative_1 },
  BufferLineTabClose                  = { fg = colors.foreground_3, bg = colors.background_negative_1 },
  BufferLineModified                  = { fg = colors.foreground_0, bg = colors.background_negative_1 },
  BufferLineWarning                   = { fg = colors.foreground_3, bg = colors.background_negative_1, sp = colors.yellow },
  BufferLineHint                      = { fg = colors.foreground_3, bg = colors.background_negative_1, sp = colors.blue },
  BufferLineInfo                      = { fg = colors.foreground_3, bg = colors.background_negative_1, sp = colors.purple },
  BufferLineError                     = { fg = colors.foreground_3, bg = colors.background_negative_1, sp = colors.red },
  BufferLineInfoDiagnostic            = { fg = colors.foreground_4, bg = colors.background_negative_1, sp = colors.purple },
  BufferLineHintDiagnostic            = { fg = colors.foreground_4, bg = colors.background_negative_1, sp = colors.blue },
  BufferLineErrorDiagnostic           = { fg = colors.foreground_4, bg = colors.background_negative_1, sp = colors.red },
  BufferLineWarningDiagnostic         = { fg = colors.foreground_4, bg = colors.background_negative_1, sp = colors.purple },
}

plugins["hrsh7th/nvim-cmp"] = {
  CmpItemAbbrMatch         = { fg = colors.accent },
  CmpItemAbbrMatchFuzzy    = { fg = colors.accent },
  CmpItemKind              = { fg = colors.foreground_2 },
  CmpItemKindColor         = { fg = colors.foreground_2 },
  CmpItemKindFile          = { fg = colors.foreground_2 },

  CmpItemAbbr              = { fg = colors.foreground_3 },
  CmpItemKindText          = { fg = colors.foreground_3 },
  CmpItemMenu              = { fg = colors.foreground_3 },
  CmpItemAbbrDeprecated    = { fg = colors.foreground_3 },

  CmpItemKindSnippet       = { fg = colors.yellow },

  CmpItemKindValue         = { link = "TSConstant" },
  CmpItemKindFolder        = { link = "Directory" },
  CmpItemKindUnit          = { link = "TSConstructor" },
  CmpItemKindField         = { link = "TSConstructor" },
  CmpItemKindEnumMember    = { link = "TSConstructor" },
  CmpItemKindStruct        = { link = "TSConstructor" },
  CmpItemKindEnum          = { link = "TSConstructor" },
  CmpItemKindConstructor   = { link = "TSConstructor" },
  CmpItemKindReference     = { link = "TSTextReference" },
  CmpItemKindEvent         = { link = "TSMethod" },
  CmpItemKindTypeParameter = { link = "TSParameter" },
  CmpItemKindProperty      = { link = "TSProperty" },
  CmpItemKindMethod        = { link = "TSMethod" },
  CmpItemKindConstant      = { link = "TSConstant" },
  CmpItemKindOperator      = { link = "TSOperator" },
  CmpItemKindFunction      = { link = "TSFunction" },
  CmpItemKindVariable      = { link = "TSVariableBuiltin" },
  CmpItemKindClass         = { link = "TSMacro" },
  CmpItemKindModule        = { link = "TSNamespace" },
  CmpItemKindKeyword       = { link = "TSKeyword" },
  CmpItemKindInterface     = { link = "TSKeyword" },
}

plugins["SmiteshP/nvim-navic"] = {
  NavicText               = { fg = colors.foreground_3 },
  NavicSeparator          = { fg = colors.foreground_3 },
  NavicIconsFile          = { link = "Directory" },
  NavicIconsModule        = { link = "TSNamespace" },
  NavicIconsNamespace     = { link = "TSNamespace" },
  NavicIconsPackage       = { link = "TSNamespace" },
  NavicIconsClass         = { link = "TSStorageClass" },
  NavicIconsMethod        = { link = "TSMethod" },
  NavicIconsProperty      = { link = "TSProperty" },
  NavicIconsField         = { link = "TSProperty" },
  NavicIconsConstructor   = { link = "TSConstructor" },
  NavicIconsEnum          = { link = "TSConstructor" },
  NavicIconsInterface     = { link = "TSKeyword" },
  NavicIconsFunction      = { link = "TSFunction" },
  NavicIconsVariable      = { link = "TSVariableBuiltin" },
  NavicIconsConstant      = { link = "TSConstant" },
  NavicIconsString        = { link = "TSString" },
  NavicIconsNumber        = { link = "TSNumber" },
  NavicIconsBoolean       = { link = "TSBoolean" },
  NavicIconsArray         = { link = "TSConstant" },
  NavicIconsObject        = { link = "TSConstant" },
  NavicIconsKey           = { link = "TSKeyword" },
  NavicIconsNull          = { link = "TSKeyword" },
  NavicIconsEnumMember    = { link = "TSConstructor" },
  NavicIconsStruct        = { link = "TSConstructor" },
  NavicIconsEvent         = { link = "TSMethod" },
  NavicIconsOperator      = { link = "TSOperator" },
  NavicIconsTypeParameter = { link = "TSParameter" },

}

plugins["lukas-reineke/indent-blankline.nvim"] = {
  IndentBlanklineChar               = { fg = colors.background_4, nocombine = true },
  IndentBlanklineSpaceChar          = { fg = colors.background_4, nocombine = true },
  IndentBlanklineSpaceCharBlankline = { fg = colors.foreground_3, nocombine = true },
  IndentBlanklineContextSpaceChar   = { fg = colors.background_4, nocombine = true },
  IndentBlanklineContextChar        = { fg = colors.foreground_3, nocombine = true },
}

plugins["folke/todo-comments.nvim"] = {
  TodoBgNOTE   = { fg = colors.background_0, bg = colors.blue, bold = true },
  TodoSignNOTE = { fg = colors.blue, bg = colors.background_0 },
  TodoFgNOTE   = { fg = colors.blue },
  TodoBgWARN   = { fg = colors.background_0, bg = colors.yellow, bold = true },
  TodoSignWARN = { fg = colors.yellow, bg = colors.background_0 },
  TodoFgWARN   = { fg = colors.yellow },
  TodoBgHACK   = { fg = colors.background_0, bg = colors.yellow, bold = true },
  TodoSignHACK = { fg = colors.yellow, bg = colors.background_0 },
  TodoFgHACK   = { fg = colors.yellow },
  TodoBgTEST   = { fg = colors.background_0, bg = colors.purple, bold = true },
  TodoSignTEST = { fg = colors.purple, bg = colors.background_0 },
  TodoFgTEST   = { fg = colors.purple },
  TodoBgTODO   = { fg = colors.background_0, bg = colors.purple, bold = true },
  TodoSignTODO = { fg = colors.purple, bg = colors.background_0 },
  TodoFgTODO   = { fg = colors.purple },
  TodoBgPERF   = { fg = colors.background_0, bg = colors.purple, bold = true },
  TodoSignPERF = { fg = colors.purple, bg = colors.background_0 },
  TodoFgPERF   = { fg = colors.purple },
  TodoBgFIX    = { fg = colors.background_0, bg = colors.red, bold = true },
  TodoSignFIX  = { fg = colors.red, bg = colors.background_0 },
  TodoFgFIX    = { fg = colors.red },
}

return plugins
